-- =============================================================================
-- LEXHUB — `anon` DAN UPDATE / DELETE / TRUNCATE HUQUQINI QAYTARIB OLISH
-- Sana: 2026-09-03
-- Ishga tushirish: Supabase Dashboard -> SQL Editor -> BUTUN faylni RUN
-- =============================================================================
-- O'LCHANGAN HOLAT (2026-09-03, JONLI production baza, vosita:
-- `tool/anon_write_privilege_zero_rows_probe.py`, filtr `?id=is.null` —
-- ya'ni `WHERE id IS NULL`, 0 QATOR o'zgardi):
--
--   jadval                PATCH          DELETE         HTTP
--   profiles              GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   questions             GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   answers               GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   question_categories   GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   question_tags         GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   bookmarks             GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   reports               GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   payments              GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   user_documents        GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   user_notifications    GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   consultations         GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   expert_profiles       GRANT MAVJUD   GRANT MAVJUD   204 | 204
--   client_error_logs     GRANT MAVJUD   GRANT MAVJUD   204 | 204
--
-- PROBE VAKUUM EMAS (ijobiy nazorat o'sha yurishda):
--   GET /rest/v1/profiles?select=phone -> HTTP 401, `42501`
--   "permission denied for table profiles"
-- Ya'ni bu HTTP yo'li `42501` ni KO'RSATA OLADI (`20260829120000` dagi
-- ustun-darajali REVOKE ishlaydi) — demak yuqoridagi 204 lar "detektor
-- ko'r" degani EMAS, huquq HAQIQATAN bor.
--
-- BU AKTIV EKSPLUATATSIYA EMAS — ATAYLAB ANIQ AYTAMAN (§0):
-- 204 = "huquq bor va 0 qator o'zgardi". Yozish HOZIR RLS bilan to'siladi.
-- Jonli RLS holati o'lchangan: `20260830100000...sql:26-31` —
-- `bookmarks`/`question_categories`/`question_tags`/`question_tag_mappings`
-- da RLS YOQILGAN va policy 0 (DENY-ALL), qolgan jadvallarda esa policy'lar
-- mavjud. Ya'ni HOZIR mehmon hech nimani o'zgartira olmaydi.
--
-- UNDA NIMA UCHUN KERAK: yaxlitlik BUTUNLAY bitta qatlamga — RLS policy
-- matniga — tayanadi. Bitta `USING (true)` yozib qo'yilsa yoki yangi
-- jadvalga RLS yoqish esdan chiqsa, mehmon DARHOL yozadi va buni HECH NARSA
-- aytmaydi. GRANT olib tashlansa, xato qilish uchun IKKI qatlamni birdan
-- buzish kerak bo'ladi. Bu — defence-in-depth, "tuzatish" emas.
--
-- REGRESSIYA XAVFI — O'LCHANDI (grep, 2026-09-03): `lib/` da masofaviy
-- yozish FAQAT 5 joyda va HAMMASI sessiya talab qiladi:
--   auth_remote_datasource.dart:204            -> o'z profilini update
--   community_forum_remote_datasource.dart:649 -> `.eq('user_id', currentUserId)`
--   community_forum_remote_datasource.dart:709 -> `currentUserId == null` gate
--   document_templates_remote_datasource.dart:137 -> `currentUserId != null` gate
--   document_templates_remote_datasource.dart:175 -> `currentUserId == null` return
-- Sessiya bo'lsa PostgREST roli `authenticated` bo'ladi, `anon` EMAS. Ya'ni
-- ilovada `anon` UPDATE/DELETE ni ishlatadigan yo'l YO'Q.
--
-- TEGILMAYDIGAN NARSALAR (ataylab, tor blast radius):
--   * SELECT — tegilmaydi. Mehmon tasmasi, kategoriya ro'yxati, mutaxassis
--     profillari O'QILISHDA QOLADI (`20260903000000` qator ko'rinishini
--     alohida cheklaydi).
--   * INSERT — tegilmaydi. `client_error_logs` ga anon INSERT LOYIHA
--     DIZAYNI (`20260830010000:140`) va u SAQLANADI — mehmon qurilmasidagi
--     xato hisoboti yo'qolmaydi.
--   * `authenticated` roli — tegilmaydi. Bu rol `anon` dan huquq MEROS
--     OLMAYDI (isbot: `profiles.phone` dan anon SELECT olib tashlangan,
--     autentifikatsiyalangan foydalanuvchi esa hozir ham o'qiydi).
--
-- KATALOG O'LCHOVI (2026-09-02T19:34:09Z, rol `postgres`,
-- `has_table_privilege('anon', c.oid, ...)` butun `public` sxema bo'yicha;
-- nusxa: `.runtime_evidence/before_anon_hardening.out.json`) — yuqoridagi
-- HTTP jadvalini MUSTAQIL ikkinchi usul bilan tasdiqlaydi:
--
--   jami obyekt (relkind r/v/p/m)  25
--   UPDATE huquqi bor              25   (istisno YO'Q)
--   DELETE huquqi bor              25   (istisno YO'Q)
--   TRUNCATE huquqi bor            25   (istisno YO'Q)
--   SELECT huquqi bor              24   (YO'Q: `profiles` — `20260829120000`)
--   INSERT huquqi bor              24
--
-- Ya'ni HTTP probe 13 jadvalni sinagan, katalog esa 25 obyektning HAMMASIDA
-- huquq borligini ko'rsatdi — REVOKE doirasi shu 25 obyektga to'g'ri keladi.
--
-- TRUNCATE — TASDIQLANGAN IKKI HUQUQDAN TASHQARIDA, SABABI ALOHIDA:
-- `TRUNCATE` RLS'ga BO'YSUNMAYDI (PostgreSQL semantikasi) — ya'ni yuqorida
-- tasvirlangan "RLS to'sadi" himoyasi TRUNCATE uchun MAVJUD EMAS. Hozir u
-- PostgREST orqali chaqirilmaydi (PostgREST faqat SELECT/INSERT/UPDATE/
-- DELETE/RPC yuboradi), shuning uchun aktiv xavf yo'q. Grant holati ilgari
-- O'LCHANMAGAN edi (PostgREST orqali o'lchash yo'li yo'q) — yuqoridagi
-- katalog o'lchovi bu bo'shliqni yopdi: huquq 25/25 obyektda BOR.
-- Olib tashlanadi: narxi nol, ilovada ishlatilmaydi, va bu — RLS
-- backstop'i YO'Q yagona yozish huquqi.
--
-- HALOL CHEKLOV — `ALTER DEFAULT PRIVILEGES` faqat MA'LUM ROL yaratgan
-- obyektlarga ta'sir qiladi. Bu TAXMIN emas, O'LCHANGAN BO'SHLIQ:
-- `pg_default_acl` da `public` sxema jadvallari uchun IKKI yozuv bor
-- (2026-09-02, o'sha nusxa fayli):
--
--   defaclrole      schema  objtype  acl (qisqartirilgan)
--   postgres        public  r        ... anon=arwdDxtm/postgres ...
--   supabase_admin  public  r        ... anon=arwdDxtm/supabase_admin ...
--
-- `arwdDxtm` ichida `w` (UPDATE), `d` (DELETE), `D` (TRUNCATE) bor. Pastdagi
-- statement FAQAT BIRINCHI yozuvni tuzatadi.
--
-- IKKINCHISI SHU YERDAN TUZATILMAYDI — O'LCHANDI. `postgres` roli
-- `supabase_admin` a'zosi EMAS (`pg_has_role('postgres','supabase_admin',
-- 'MEMBER') = false`), va urinish JONLI bazada shu xatoni qaytardi
-- (BEGIN ... ROLLBACK ichida sinaldi, HECH NARSA o'zgarmadi):
--
--   ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
--       REVOKE UPDATE, DELETE, TRUNCATE ON TABLES FROM anon;
--   -> ERROR: 42501: permission denied to change default privileges
--
-- Shuning uchun bu faylga o'sha statement QO'SHILMADI: u tranzaksiyani
-- YIQITARDI va butun migratsiya qo'llanmasdan qolardi. QOLDIQ XAVF ANIQ
-- AYTILADI: agar kelajakda `public` sxemada jadval `supabase_admin` nomidan
-- yaratilsa, `anon` unga UPDATE/DELETE/TRUNCATE bilan tug'iladi. Amalda
-- Supabase o'z obyektlarini `auth`/`storage`/`realtime` sxemalarida
-- yaratadi, `public` esa migratsiya/SQL Editor (ya'ni `postgres`) hududi —
-- lekin bu KAFOLAT EMAS.
--
-- KOMPENSATSIYA (detektor, oxirdagi tekshiruv bo'limida): qo'llagandan
-- keyin va yangi jadval qo'shilgan har safar katalog so'rovi yurgiziladi —
-- `anon` da UPDATE/DELETE/TRUNCATE bor obyekt QOLGANI ko'rinadi. Ya'ni
-- pastdagi ikkinchi statement HIMOYA EMAS, faqat "sukut bo'yicha kamroq
-- huquq"; yangi jadval qo'shilganda RLS'ni YOQISH va detektorni QAYTA
-- yurgizish SHART.
--
-- QAYTARISH (rollback) fayl oxirida. MA'LUMOT YO'QOLMAYDI: bu faylda
-- birorta `DELETE`, `UPDATE`, `DROP` yoki `TRUNCATE` BAJARILMAYDI — faqat
-- huquq (`ACL`) o'zgaradi.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1) MAVJUD JADVALLAR — UPDATE va DELETE ni `anon` dan olib tashlash
-- -----------------------------------------------------------------------------
-- `ON ALL TABLES IN SCHEMA public` view'larni ham qamrab oladi (PostgreSQL
-- uchun view ham "table"). View'lar `anon` uchun faqat O'QISH manbai
-- (`public_expert_profiles_view` — `20260829000500:85`), shuning uchun
-- ularda UPDATE/DELETE yo'qolishi hech nimani buzmaydi.
REVOKE UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM anon;

-- Yuqoridagi "TRUNCATE" izohiga qara: RLS backstop'i bo'lmagan yagona
-- yozish huquqi. Alohida statement — alohida qaytarish uchun.
REVOKE TRUNCATE ON ALL TABLES IN SCHEMA public FROM anon;

-- -----------------------------------------------------------------------------
-- 2) KELAJAKDAGI JADVALLAR — sukut bo'yicha huquqni kamaytirish
-- -----------------------------------------------------------------------------
-- Supabase `public` sxemasi uchun `ALTER DEFAULT PRIVILEGES ... GRANT ALL ON
-- TABLES TO anon` o'rnatgan (`20260830100000:61-63` da hujjatlashtirilgan).
-- Ya'ni BUGUN yaratilgan har yangi jadval `anon` ga to'liq yozish huquqi
-- bilan tug'iladi. Quyidagi statement shu sukutni tuzatadi.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
    REVOKE UPDATE, DELETE, TRUNCATE ON TABLES FROM anon;

COMMIT;

-- =============================================================================
-- QO'LLAGANDAN KEYIN TEKSHIRISH
-- =============================================================================
-- 0) KATALOG DETEKTORI (yagona ISHONCHLI o'lchov — RLS bilan chalkashmaydi.
--    HTTP probe'da 0-qator va RLS-rad bir xil ko'rinadi, katalog esa AYNAN
--    huquqni aytadi). Bo'sh natija = `anon` da yozish huquqi QOLMADI.
--    YANGI jadval qo'shilgan HAR SAFAR ham shu so'rov yurgiziladi:
--
--      SELECT c.relname,
--             has_table_privilege('anon', c.oid, 'UPDATE')   AS upd,
--             has_table_privilege('anon', c.oid, 'DELETE')   AS del,
--             has_table_privilege('anon', c.oid, 'TRUNCATE') AS trunc
--        FROM pg_class c
--       WHERE c.relnamespace = 'public'::regnamespace
--         AND c.relkind IN ('r','v','p','m')
--         AND (has_table_privilege('anon', c.oid, 'UPDATE')
--           OR has_table_privilege('anon', c.oid, 'DELETE')
--           OR has_table_privilege('anon', c.oid, 'TRUNCATE'))
--       ORDER BY 1;
--
-- =============================================================================
-- QO'LLANDI — JONLI PRODUCTION BAZASIDA O'LCHANGAN NATIJA
-- =============================================================================
-- QO'LLASH: 2026-09-02 (UTC), `supabase db query --linked -f <shu fayl>`,
-- rol `postgres`. Katalog nusxalari (OLDIN 19:34:09Z, KEYIN 19:54:04Z):
--   `.runtime_evidence/before_anon_hardening.out.json`
--   `.runtime_evidence/after_anon_hardening.out.json`
--
-- 1) KATALOG DETEKTORI (yuqoridagi 0-bosqich so'rovi) — `anon` da yozish
--    huquqi QOLGAN obyekt: BO'SH natija. Ya'ni:
--
--      huquq        OLDIN        KEYIN
--      UPDATE       25 / 25      0 / 25
--      DELETE       25 / 25      0 / 25
--      TRUNCATE     25 / 25      0 / 25
--      SELECT       24 / 25      24 / 25   <- TEGILMADI
--      INSERT       24 / 25      24 / 25   <- TEGILMADI
--
--    SELECT va INSERT sonlari O'ZGARMADI — mehmon tasmasi va
--    `client_error_logs` INSERT yo'li tirik qoldi (statik emas, O'LCHANGAN).
--
-- 2) MUSTAQIL IKKINCHI USUL — ANON KALIT BILAN HTTP probe (nusxa:
--    `.runtime_evidence/anon_write_probe_AFTER.txt`):
--
--      python tool/anon_write_privilege_zero_rows_probe.py
--
--    13 jadvalning HAMMASIDA PATCH va DELETE -> `GRANT-RAD` (`42501`).
--    OLDIN o'sha 13 jadvalda `GRANT MAVJUD` (HTTP 204) edi — fayl boshidagi
--    jadvalga qara. Ijobiy nazorat o'zgarmadi: `profiles?select=phone` ->
--    HTTP 401 `42501` ("detektor ISHLAYDI").
--
-- 3) SUKUT HUQUQI (`pg_default_acl`, KEYIN o'lchandi):
--
--      defaclrole      objtype  anon ACL
--      postgres        r        arxtm      <- `w`,`d`,`D` OLINDI
--      supabase_admin  r        arwdDxtm   <- O'ZGARMADI (yuqoridagi cheklov)
--
--    Ya'ni yuqorida yozilgan QOLDIQ XAVF o'lchov bilan TASDIQLANDI: agar
--    `public` sxemada jadval `supabase_admin` nomidan yaratilsa, `anon` unga
--    yozish huquqi bilan tug'iladi. Detektor (0-bosqich) shu holatni ko'radi.
--
-- 4) REGRESSIYA — `tool/anon_privilege_probe_precise.py` QAYTA yurgizildi
--    (nusxa: `.runtime_evidence/anon_precise_AFTER.txt`): anonim savol
--    himoyasi, `is_admin_or_moderator` -> false va `global_search` -> 5 qator
--    O'ZGARMADI.
--
--    `client_error_logs` ga anon INSERT ATAYLAB SINALMAYDI: u audit yozuvi,
--    DELETE policy'si YO'Q (`20260830010000` — "yozuv o'zgartirilmaydi"), ya'ni
--    sinov production'da QAYTARIB BO'LMAYDIGAN qator qoldiradi. Buning
--    o'rniga KATALOG o'lchandi (yuqoridagi 1-band: INSERT 24 -> 24), ya'ni
--    huquq saqlanganiga ISBOT bor, qator qoldirmasdan.
--
-- =============================================================================
-- QAYTARISH (ROLLBACK) — ma'lumot YO'QOLMAYDI, faqat ACL tiklanadi
-- =============================================================================
-- BEGIN;
--   GRANT UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO anon;
--   ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
--       GRANT UPDATE, DELETE, TRUNCATE ON TABLES TO anon;
-- COMMIT;
--
-- DIQQAT: yuqoridagi `GRANT` Supabase'ning ASL holatini TAXMINAN tiklaydi.
-- Agar biror jadvalda huquq boshqacha (masalan ustun-darajali) berilgan bo'lsa,
-- bu rollback uni AYNAN qaytarmaydi. Shuning uchun qo'llashdan oldin ACL
-- nusxasini olish tavsiya etiladi (SQL Editor, service_role bilan):
--   SELECT relname, relacl FROM pg_class
--    WHERE relnamespace = 'public'::regnamespace AND relkind IN ('r','v','p');
